services:
  - type: web
    name: flask-sqlalchemy-app
    env: python
    plan: free            
    region: oregon         
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers=2"
    preDeployCommand: "flask db upgrade"   
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: flask-db
          property: connectionString

databases:
  - name: flask-db
    plan: free
    ipAllowList: []  
